version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: Amits-MacBook-Pro.local
    command:  bash -c 'rabbitmq-plugins enable rabbitmq_stomp && rabbitmq-server'
    volumes:
      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
      - 61613:61613
